# A program that computes how a target sum can be generated by adding elements in the numbers array using tabulation
def how_sum(number, array):
    table = [None] * (number + 1)
    table[0] = []
    current = 0
    while current <= number:
        if table[current] is not None:
            for element in array:
                if element + current <= number:
                    table[current + element] = table[current] + [element]
        current += 1
    return table[number]


print(how_sum(7, [5, 3, 4]))
print(how_sum(7, [5, 3, 4, 7]))
print(how_sum(7, [2, 4]))
print(how_sum(8, [2, 3, 5]))
print(how_sum(300, [7, 14]))
